### PR TITLE
Fix the profiler driver 

### LINKED ISSUE #490: Fix the profiler driver
A bug is found: 
```
micm/examples/profile_example.cpp:55:3: error: unknown type name 'ConfigParseStatus'
  ConfigParseStatus status = solverConfig.ReadAndParse(config_path);
```

### PR DESCRIPTION
**Pull request by boulderdaze**
Closes #490 

Removed the outdated `ConfigParseStatus` 
Added it to the git actions

### CODE REVIEW

**Review by K20shores — APPROVED** [review]
Does this get run in any of the github actions?

**Comment by boulderdaze** [comment]
> Does this get run in any of the github actions?

Looks like it doesn't. If `MICM_ENABLE_PROFILE` is `ON`, the executable is created but the default is `OFF` unlike `MICM_ENABLE_EXAMPLES`, which makes sense. I'd like to have it added to the github actions but am not sure which is the best way to do. Creating a docker for this could be easier but am not sure that's what we want to do. What do you think?

**Comment by K20shores** [comment]
@boulderdaze I think it makes sense to add this option to the mac, ubuntu, and windows actions

**Comment by boulderdaze** [comment]
> @boulderdaze I think it makes sense to add this option to the mac, ubuntu, and windows actions

**Comment by boulderdaze** [comment]
> @boulderdaze I think it makes sense to add this option to the mac, ubuntu, and windows actions

Yes, I updated it. Could you review them one more?

**Review by K20shores — APPROVED** [review]

**Pull request merged**
