### PR TITLE
Add MOZART LU decomposition scheme

### LINKED ISSUE #685: Implement the CAM-chem LU decomposition algorithm in MICM
We want to implement the CAM-chem algorithm for LU decomposition in MICM, and evaluate its performance against the Fortran version later.

**Acceptance Criteria**

- C++ decomposition classes can use the CAM-chem algorithm for LU decomposition
- All current tests pass
- Documentation referring to the new implementation is added
- The CUDA and JIT implementations can be done in a separate issue if we find this implementation is necessary.

**Ideas**

The pseudo code based on the preprocessor source code (https://github.com/ESCOMP/CHEM_PREPROCESSOR/blob/f923081508f4264e61fcef2753a9898e55d1598e/src/cam_chempp/make_lu_fac.f#L127-L214) may be:
```
for i = 0…n-1
       if (A[i][i] != 0) A[i][i] = 1 / A[i][i]
       for j = i+1…n-1
             if (A[j][i] != 0) A[j][i] = A[j][i] * A[i][i]
       for k = i+1…n-1
             if (A[i][k] != 0)
             {
                  for j = i+1…n-1
                        if (A[j][i] != 0)
                        {
                            if (A[j][k] != 0) 
                               A[j][k] = A[j][k] – A[j][i] * A[i][k] 
                           else
                               A[j][k] = - A[j][i] * A[i][k]
                        }
             }
```

### PR DESCRIPTION
**Pull request by mattldawson**
Add the MOZART LU decomposition scheme.

closes #685

Also:
- creates an alias for the default LU decomposition scheme (currently Doolittle) named `LuDecomposition`. This will allow us to change the default scheme more easily, just by changing the alias to point to the new scheme.

### CODE REVIEW

**Review by K20shores — CHANGES_REQUESTED** [review]
Can you setup one of the integration tests with a solver builder that uses the mozart LU decomp?

**Review by sjsprecious — COMMENTED** [review]
Thanks @mattldawson for working on this giant implementation.

Looks like the [new implementation](https://github.com/NCAR/micm/actions/runs/12169539240/job/33942677529#step:5:976) is even slower than the [Doolittle version](https://github.com/NCAR/micm/actions/runs/12169539240/job/33942677529#step:5:790), and I observed similar behavior on Derecho, too.

**Comment by mattldawson** [comment]
> Can you setup one of the integration tests with a solver builder that uses the mozart LU decomp?

done!

**Review by sjsprecious — APPROVED** [review]
Looks nice! Thanks for working on this.

**Pull request merged**
