### PR TITLE
416 add assignment overridescopy constructors to cudavectormatrix so new matrix has separate device memory

### PR DESCRIPTION
**Pull request by mwaxmonsky**
Adds assignment and move operators and constructors so a CudaVectorMatrix can be assigned to another  which generates new device data for the newly assigned vector or moves the other vector into the new vector while in that case taking ownership of the other matrix's device memory.

### CODE REVIEW

**Review by sjsprecious — APPROVED** [review]
Thanks @mwaxmonsky for fixing this issue. All the tests passed on Derecho's GPU.

Would it be helpful to add some comments about the overrided operator?

**Review by mattldawson — APPROVED** [review]
nice!

**Comment by mwaxmonsky** [comment]
> Thanks @mwaxmonsky for fixing this issue. All the tests passed on Derecho's GPU.
> 
> Would it be helpful to add some comments about the overrided operator?

Is this in regards to the 4 move/copy assignment/constructors?  If so, after talking with @mattldawson, it sounds like we don't want to add comments stating what each operator/constructor is since they are inferred by their signature.

But if this is in relation to different comments, just let me know and I'd be happy to add it!

**Review by sjsprecious — APPROVED** [review]
All the tests still passed on Derecho's GPU.

**Pull request merged**
